version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor:
        update-types:
          - "minor"
          - "patch"
      actions-major:
        update-types:
          - "major"
