name: Build Development Containers Image

on:
  workflow_call:
  schedule:
    - cron: '30 9 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        version:
          # Latest tags
          - latest
          - focal
          - jammy
          - noble
          # Nightly latest tags
          - nightly
          - nightly-focal
          - nightly-jammy
          - nightly-noble
          # Nightly main
          - nightly-main
          - nightly-main-focal
          - nightly-main-jammy
          - nightly-main-noble
          # Version
          ## Swift 5.2 and 5.3 (has patch version in 1...3, this devcontainer not supported)
          - 5.2-focal
          - nightly-5.3-focal
          - 5.3-focal
          ## Swift 5.4 (first release with patch 0, first support for patch version specific)
          - nightly-5.4-focal
          - 5.4-focal
          - 5.4.0-focal
          - 5.4.1-focal
          - 5.4.2-focal
          - 5.4.3-focal
          ## Swift 5.5
          - nightly-5.5-focal
          - 5.5-focal
          - 5.5.0-focal
          - 5.5.1-focal
          - 5.5.2-focal
          - 5.5.3-focal
          ## Swift 5.6
          - nightly-5.6-focal
          - 5.6-focal
          - 5.6.0-focal
          - 5.6.1-focal
          - 5.6.2-focal
          - 5.6.3-focal
          ## Swift 5.7 (start based ubuntu:jammy)
          - nightly-5.7-focal
          - nightly-5.7-jammy
          - 5.7-focal
          - 5.7-jammy
          - 5.7.0-focal
          - 5.7.0-jammy
          - 5.7.1-focal
          - 5.7.1-jammy
          - 5.7.2-focal
          - 5.7.2-jammy
          - 5.7.3-focal
          - 5.7.3-jammy
          ## Swift 5.8
          - nightly-5.8-focal
          - nightly-5.8-jammy
          - 5.8-focal
          - 5.8-jammy
          - 5.8.0-focal
          - 5.8.0-jammy
          - 5.8.1-focal
          - 5.8.1-jammy
          ## Swift 5.9
          - nightly-5.9-focal
          - nightly-5.9-jammy
          - 5.9-focal
          - 5.9-jammy
          - 5.9.0-focal
          - 5.9.0-jammy
          - 5.9.1-focal
          - 5.9.1-jammy
          - 5.9.2-focal
          - 5.9.2-jammy
          ## Swift 5.10 (start stable based ubuntu:noble)
          - nightly-5.10-focal
          - nightly-5.10-jammy
          - 5.10-focal
          - 5.10-jammy
          - 5.10-noble
          - 5.10.0-focal
          - 5.10.0-jammy
          - 5.10.0-noble
          - 5.10.1-focal
          - 5.10.1-jammy
          - 5.10.1-noble
          ## Swift 6.0
          - nightly-6.0-focal
          - nightly-6.0-jammy
          - 6.0-focal
          - 6.0-jammy
          - 6.0-noble
          - 6.0.0-focal
          - 6.0.0-jammy
          - 6.0.0-noble
          - 6.0.1-focal
          - 6.0.1-jammy
          - 6.0.1-noble
          - 6.0.2-focal
          - 6.0.2-jammy
          - 6.0.2-noble
          - 6.0.3-focal
          - 6.0.3-jammy
          - 6.0.3-noble
          ## Swift 6.1 (start nightly based ubuntu:noble)
          - nightly-6.1-focal
          - nightly-6.1-jammy
          - nightly-6.1-noble
          - 6.1-focal
          - 6.1-jammy
          - 6.1-noble
          - 6.1.0-focal
          - 6.1.0-jammy
          - 6.1.0-noble
          - 6.1.1-focal
          - 6.1.1-jammy
          - 6.1.1-noble
          - 6.1.2-focal
          - 6.1.2-jammy
          - 6.1.2-noble
          - 6.1.3-focal
          - 6.1.3-jammy
          - 6.1.3-noble
          ## Swift 6.2 (drop stable based ubuntu:focal)
          - nightly-6.2-focal
          - nightly-6.2-jammy
          - nightly-6.2-noble
          - 6.2-jammy
          - 6.2-noble
          - 6.2.0-jammy
          - 6.2.0-noble
          - 6.2.1-jammy
          - 6.2.1-noble
          - 6.2.2-jammy
          - 6.2.2-noble
          - 6.2.3-jammy
          - 6.2.3-noble
          - 6.2.4-jammy
          - 6.2.4-noble
          ## Next Swift 6.3 (drop nightly based ubuntu:focal)
          - nightly-6.3-jammy
          - nightly-6.3-noble

        include:
          # nightly main use main branch of swift-format
          - version: nightly
            format: main
          - version: nightly-focal
            format: main
          - version: nightly-jammy
            format: main
          - version: nightly-noble
            format: main
          - version: nightly-main
            format: main
          - version: nightly-main-focal
            format: main
          - version: nightly-main-jammy
            format: main
          - version: nightly-main-noble
            format: main

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup templates via Dev Container CLI
        run: |
          npm install -g @devcontainers/cli
          devcontainer templates apply \
            -t ghcr.io/kphrx/swift-devcontainer-template/${{ startsWith(matrix.version, 'nightly-') && 'nightly' || 'stable' }} \
            -a '{"imageVariant": "${{ matrix.version }}", "swiftFormatBranch": "${{ matrix.format || 'auto' }}"}' \
            -w ./${{ matrix.version }}

      - name: Pre-build dev container image with alias tag
        if: ${{ matrix.tag }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subFolder: ${{ matrix.version }}
          imageTag: ${{ matrix.version }},${{ matrix.tag }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
          push: always

      - name: Pre-build dev container image
        if: ${{ !matrix.tag }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subFolder: ${{ matrix.version }}
          imageTag: ${{ matrix.version }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
          push: always
