name: Release Dev Container Templates

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Publish Templates
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-templates: true
          templates-namespace: ${{ github.repository }}-template
          base-path-to-templates: ./src
          publish-features: true
          features-namespace: ${{ github.repository }}-feature
          base-path-to-features: ./src

  build:
    uses: ./.github/workflows/build.yml
    needs: [deploy]
    permissions:
      contents: read
      packages: write
      id-token: write
