name: Release Dev Container Templates

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    strategy:
      matrix:
        type:
          - template
          - feature

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish ${{ matrix.type }}s
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-${{ matrix.type }}s: true
          ${{ matrix.type }}s-namespace: ${{ github.repository }}-${{ matrix.type }}
          base-path-to-${{ matrix.type }}s: ./${{ matrix.type }}s

  build:
    uses: ./.github/workflows/build.yml
    needs: [deploy]
    permissions:
      contents: read
      packages: write
      id-token: write
